apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: authelia
spec:
  template:
    spec:
      containers:
        - name: authelia
          env:
            - name: AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE
              value: /postgres-secrets/POSTGRES_STORAGE_PASSWORD
