pod:
  probes:
    startup:
      initialDelaySeconds: 5
ingress:
  enabled: true
  tls:
    enabled: false
  traefikCRD:
    enabled: true
    sticky: true
    entryPoints:
      - websecure
    middleware:
      name:
        chainIngress: headers-authelia
secret:
  additionalSecrets:
    authelia-postgres-app:
      items:
        - key: password
          path: postgres-password
    authelia-oidc-secrets: {}
    authelia:
      items:
        - key: oidc.jwk.RS256.pem
          path: oidc.jwk.RS256.pem
  existingSecret: authelia
configMap:
  theme: dark
  authentication_backend:
    password_reset:
      # TODO: remove once LDAP is in place
      disable: true
    file:
      enabled: false
    ldap:
      enabled: true
      address: ldaps://openldap.auth.svc.cluster.local:636
      additional_users_dn: OU=users
      base_dn: DC=simulatan,DC=me
      users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
      groups_filter: (&(member={dn})(objectClass=groupOfNames))
      user: UID=authelia,OU=service,DC=simulatan,DC=me
      tls:
        skip_verify: true
      attributes:
        username: uid
        display_name: displayName
        mail: mail
        picture: picture
  webauthn:
    enable_passkey_login: true
  identity_providers:
    oidc:
      enabled: true
      lifespans:
        access_token: '7 days'
        id_token: '10 hours'
        refresh_token: '14 days'
      hmac_secret:
        path: 'oidc.hmac.secret'
      jwks:
        - algorithm: 'RS256'
          use: 'sig'
          key:
            path: '/secrets/authelia/oidc.jwk.RS256.pem'
  identity_validation:
    reset_password:
      secret:
        path: 'oidc.hmac.key'
  notifier:
    smtp:
      enabled: true
      enabledSecret: true
      address: live.smtp.mailtrap.io:587
      port: 587
      timeout: 10s
      sender: SIMs Authelia <authelia@smtp.simulatan.me>
      username: api
      ## HELO/EHLO Identifier. Some SMTP Servers may reject the default of localhost.
      identifier: localhost
      ## Subject configuration of the emails sent.
      ## {title} is replaced by the text from the notifier
      subject: "[Auth] {title}"
      ## This address is used during the startup check to verify the email configuration is correct.
      ## It's not important what it is except if your email server only allows local delivery.
      startup_check_address: test@authelia.com
      disable_html_emails: false
      disable_require_tls: false
      disable_starttls: false

      tls:
        skip_verify: false
        minimum_version: TLS1.2
        maximum_version: TLS1.3
  log:
    level: debug
  storage:
    postgres:
      enabled: true
      address: authelia-postgres-rw.auth.svc.cluster.local
      username: authelia
      database: authelia
      password:
        secret_name: authelia-postgres-app
        path: postgres-password
      tls:
        enabled: true
        skip_verify: true
  session:
    cookies:
      - domain: simulatan.me
        subdomain: auth
    redis:
      enabled: true
      enabledSecret: false
      password:
        disabled: true
      host: authelia-redis.auth.svc.cluster.local
      port: 26379
      high_availability:
        enabled: true
        enabledSecret: false
        sentinel_name: mymaster # the default bitnami name
        password:
          disabled: true
        nodes:
          - host: authelia-redis-node-0.authelia-redis-headless.auth.svc.cluster.local # default node names with my namespace
            port: 26379
          - host: authelia-redis-node-1.authelia-redis-headless.auth.svc.cluster.local
            port: 26379
          - host: authelia-redis-node-2.authelia-redis-headless.auth.svc.cluster.local
            port: 26379
