apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth

resources:
- ./postgres-cluster.yml
- ./authelia-secret.yml
- ./authelia-oidc-secrets.yml
- ./authelia-traefik-middleware.yml

helmCharts:
- name: redis
  repo: https://charts.bitnami.com/bitnami
  version: 18.19.4
  releaseName: authelia-redis
  valuesFile: redis.values.yml
- name: authelia
  repo: https://charts.authelia.com
  version: 0.9.14
  valuesFile: authelia.values.yml
  additionalValuesFiles:
    - authelia-oidc-clients.yml
  releaseName: authelia
  namespace: auth

patches:
  - path: authelia-oidc-secrets-mount-patch.yml
    target:
      kind: DaemonSet
      labelSelector: app.kubernetes.io/name=authelia
