apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth

resources:
- ./postgres-cluster.yml
- ./authelia-secret.yml
- ./authelia-oidc-secrets.yml
- ./authelia-traefik-middleware.yml

helmCharts:
- name: valkey
  repo: oci://registry-1.docker.io/bitnamicharts
  version: 3.0.2
  releaseName: authelia-valkey
  valuesFile: valkey.values.yml
  namespace: auth
- name: authelia
  repo: https://charts.authelia.com
  version: 0.10.22
  valuesFile: authelia.values.yml
  additionalValuesFiles:
    - authelia-oidc-clients.yml
  releaseName: authelia
  namespace: auth

patches:
  - path: authelia-oidc-secrets-mount-patch.yml
    target:
      kind: DaemonSet
      labelSelector: app.kubernetes.io/name=authelia
