apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth

resources:
- ./postgres-cluster.yml
- ./authelia-secret.yml
- ./authelia-oidc-secrets.yml
- ./authelia-traefik-middleware.yml

helmCharts:
- releaseName: valkey
  name: redis-ha
  repo: https://dandydeveloper.github.io/charts
  version: 4.33.8
  valuesFile: valkey.values.yml
  namespace: auth
- name: authelia
  repo: https://charts.authelia.com
  version: 0.10.22
  valuesFile: authelia.values.yml
  additionalValuesFiles:
    - authelia-oidc-clients.yml
  releaseName: authelia
  namespace: auth

patches:
  - path: authelia-oidc-secrets-mount-patch.yml
    target:
      kind: DaemonSet
      labelSelector: app.kubernetes.io/name=authelia
