apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres-cluster
  namespace: auth
spec:
  teamId: auth
  volume:
    size: 200Mi
  numberOfInstances: 0
  users:
    authelia:
    - superuser
    - createdb
  databases:
    authelia: authelia
  postgresql:
    version: "15"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authelia-postgres
  namespace: auth
spec:
  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:15

  bootstrap:
    initdb:
      database: authelia
      owner: authelia

  postgresql:
    pg_hba:
      - local all all trust
      - host all all 127.0.0.1/32 trust
      - host all all ::1/128 trust

  storage:
    size: 1Gi
