fullnameOverride: authelia-valkey

rbac:
  create: false
serviceAccount:
  create: false

haproxy:
  enabled: false

replicas: 3

image:
  repository: valkey/valkey
  tag: 8.1-alpine

auth: true
existingSecret: authelia
authKey: redis.password

redis:
  masterGroupName: myprimary
  resources:
    requests:
      cpu: 50m
      memory: 75Mi
    limits:
      cpu: 200m
      memory: 200Mi

persistentVolume:
  size: 100Mi
