apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-auth
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgAzK5Q8Gx775LZZRUQkqCv4quJRo3DI4nWxo8BGo/sPh5eeW8CQjgZyREmBV5lppKKhHQvIf+CJUNpkYjRY3UpGM4GG9RrKV0IhsncQOiCcAVueM8Gt4H/mIqqmlb4ndA1HGx2HThWexhStOoT0+GihmnRN19ckk4haXjd9LNn+kTDi4hwKhJozbmuV8DwO2S7Wny3i6Cjj7P2s5lq6yXdpWijYAuJysZiZkkyiZDZ8/qCrATNChsrnuxWbv3xkKKe/CPddtfiywBxBAEhYsQ0UOOWR5q7YSgH0Rs6ql2Q5kbY8p/WyznX9gbFTj0C4RbDRU1st/V7S4PREZ4dman2IAPaqEWnY24gtOaSU7J4ArfY72SZXfC4fKpYG4OMUHCUprObA9Bya1UNlM0wjmO0AVAzL2bnt6X52ZdbOFBPewo5znFlL3TPyLIsDzmJ74PnuVvPAypPFNK/UNQnjEC5NAeUw6Dn2BJ3ZrtzyotmV64aiirWFHmGL3vvoG+fhpqr5rQJysIUgoA1m7qJC+e7urMT+Q2ya7uTFhNMFtyUNhGjupbM7Q/anowCInl0vC+HcIAr3WZh038oGlVOXxSAtwR2J6ocrPI1Sbjp0HlKJ21GjKwQ8DHeJlSAxPSeSm/ymUlQiBFaFEnDZPx9Xlfwm+PNRaFKYglJim32hZ2WBU992oQLfy9BkqsFVK8vraHXaMdZvCrb8KTLHOr384nqBFCGs1WaEqggCfEMJ2pdpwuvWOo2clzJr
  template:
    metadata:
      name: renovate-auth
      namespace: renovate
