---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-auth
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_GIT_AUTHOR: AgB/JCSSYq3HPmVgvX577WwwQq7HWxYYqCq5VvYOn9yAfkP5TfFskNtg4Eksv1mbOTQ1ON3yiwIkgmfSNRT69vM/uSvJJCrtxQKvW+Scz+NTtH7vYxvk8EixGq1JHHkL3WmrCz8q19JgxnSJPHKPmquc9eZgbgfM/vf9i5TOWXUFeTv5ZLl6e8dvXhbkS5wuLZhNvT+GZX9NY+eVz48IhSFfriKyGKs9wvM1dpaZxEdyaq0wRLFEz72hsKQhPESlgv+RgEtQicL379Cr6GeEeo1ZhFXg5xWXFXrXuQTG1tlOAgB2rG/9FG9Qhg4YBGgdqK1qhom5YDobXrNXDgHDViIl1dM+9wWhJUxpAtW48u9Y6a5HsSosfoyCI5K1Yvp+ljEPDRmIPKep93TkEGLGHQKvKnwLa8PJFyZNDHAfV4m8NvLg0DM4QR4+fmbCLA3A2vi0cow8Hv+RCtt2hCHKCBbqaZeOdIldeqejjFke7GMTxwOa4u54OBuO3yiha3WNrPAW9yi7kX4KodTIpdhEhlnoAjiQSUuf50lHPp3MdvLADvVSvMWY7pzKaskibyl32wzJf/w+d1pdF9sRk+CmY2HA5tEHpLbE/l6TLv52OOOys1xq6KcqZGlJ/kWQKHUF3WyJgMqZfJPDea3Z5CY0Mc1kKfMcFFk5Fofcxwr8RxQSc9AIPWHs6Y41PX+38/4/O739ZnoGnK6bO4HtMqWYTSxY3Chg4tpTW4EVFG+N4kGR/334TO0Bo6o=
    RENOVATE_TOKEN: AgAkZtY/KfrNUBYDGtPwWl1RgB9pSB9umBK0XmUfWObgz7JHsaQu4QoCKjvIuTxKYq2AczYqgKE/q+PkPlT+XiW+frC4TstAy4Qg6oovcwFuKewHB3tW3CJxhqu/3x5WPUrTcTxajG7v3SQQVKsnWUFfNwN6q11DaKk5NcSkTpsBhYRrBQO69StJ6z7edFPeYaWfolkCUi0mq2ITtdh8kauOvsEDRjfRetlpkVUvFGWmZ6jP44giFlvaAxpa6WAkYx9ycpCttGDGkkTwH0utrsdnZP8pQ8YxzhoPeFqDHWs3mgFDviHala4fpPWr/5lKUa2hHmg10nlE9iparNyyEfmEZCdkTBCxScAey8QsHUo/YmicIkCsanx5Rx8cKIIR73ErsAMMd6OEW7SA1DbctNxJOFdw9uMg6t26apFg6V0FAUYkd4BzkMbys30SGc+7nVpVs01TN5zKlCvxw9wICi0o8tdHzSBcP8DkSnC4JW440Mz99oN1viizwRBAz2weW8Y9tL6nMV9I/WxdE6YRZZEEd35x67DiMF+Qe3vOdJYeV83YVD1Y+P3kJZfHJMo9Si7PCMf492FQ1oImdF5JvbZVih00OOgot2OabUjKZe1lGx0EArJNcDt+G/iAdlnpo7PYQY/61F5EBWwEJsQOTNE/qbzTalClvnkhPygFTCLEu3YXiUA71InStOn+FojZQplVls+5jl71cRqyUoreu7Gee727NbfPu8QXkWDd61P2u3QJv/K8Gbxh
  template:
    metadata:
      name: renovate-auth
      namespace: renovate
    type: Opaque
