apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: hedgedoc-postgres
  namespace: hedgedoc
spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:17

  bootstrap:
    initdb:
      database: hedgedoc
      owner: hedgedoc

  postgresql:
    pg_hba:
      - local all all trust
      - host all all 127.0.0.1/32 trust
      - host all all ::1/128 trust

  storage:
    size: 2Gi
