apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opencloud

resources:
  - ./pvc.yml
  - ./opencloud-oidc.yml
  - ./deployment.yml
  - ./service.yml
  - ./ingress.yml

configMapGenerator:
  - name: opencloud-config
    envs:
      - ./config.env
  - name: opencloud-configs
    files:
      - ./csp.yml
      - ./proxy.yml
