apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencloud-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: storage-pool-fast
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencloud-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
  storageClassName: storage-pool-big

