helmCharts:
  - releaseName: open-feature-operator
    name: open-feature-operator
    repo: https://open-feature.github.io/open-feature-operator
    version: v0.9.1
    namespace: openfeature-operator
