apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openfeature-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SIMULATAN/k8s-ops
    path: openfeature-operator
  destination:
    name: in-cluster
