apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-grafana
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://github.com/SIMULATAN/k8s-ops
    path: monitoring/grafana
  ignoreDifferences:
  - kind: Secret
    name: grafana
    jsonPointers:
    - /data/admin-password
  destination:
    name: in-cluster
    namespace: monitoring

