apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k3s
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SIMULATAN/k8s-ops
    path: k3s
  destination:
    name: in-cluster
    namespace: system-upgrade

