apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord
  namespace: monitoring
spec:
  encryptedData:
    url: AgAxyfqsh9PawKMEkJTeIJT32Ufjcv/yUMdQRd/YpKRRM67+6jrqNTZPODBDcjdXk4nlO5DmxTSrcfGxlBM3BZdiI9XJdigD/2NhVXZwmhwoYSuZ5RAFUrLvs/H9cUQbgXjQgkiipL6PeVu2hFzqSjVVTA0UtiKLNhGHeyeSGDOGNfWtgWAbewyI/0oWV9suvS2hz23NxN69egbunIqmeibrEKLhiiYF/4gMhk5NNhuI0yQCsIOJBJpslCWjC91QJnRfT+Uay8U3TC620iug0V9Gd+lJdVtPqqXR5WCYu1tutzIRxdoMHbSEQFeP3HdaX20OCKDO7HvfG9Bf2bY5TWQW4CChKwkQGG5pU1pLuM/uDKLfo3Ot5e7vAdQTv8Bl+QUJc7Sw0iG9UkxWoGz25ndET6nlj7GbG8TcwBtIZS1qVsPmMfIU19HJI6QvIilOhpBPa5RZULaAkRM8wmGfuYTsNkEAd+RzzW8VDAAIUEOOIwEg4y5UnZ+O05A1xszhD0leDdK/uebKZ0J3l07pTOP8Wb5DLA0fb4HMvr+fTgXPZirLyD/9YRUegrZuklyVFBQ1RF66JtRZKCGQq2k4z5OyWO1RF96eh9kCYY7NnoHJ9QEMH5oFC2Mxr6lqNOQk0KO8HDmMMeFLTPU+AhA/G+vNYts6b0CQABsLM1VTaYvXwPCnF9Vxd3hVrrbtVem17xRWYTIJ9rRXq445GUKZG48MZBqTZBbG9knqVfdF/mPXOmkXhKFWtvshownCEqoMOh9Q3AL0lzGNhnji63QqEKLniGHEsiwquhI+3/kGwm67KzP+O8FGS2rtoJZ8Kbdbw8bIeRiDPrfZV0BJpAh1sTlKdqSKSNw0ahBE
  template:
    metadata:
      name: alertmanager-discord
      namespace: monitoring
