apiVersion: monitoring.grafana.com/v1alpha2
kind: PodLogs
metadata:
  name: alertmanager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: monitoring
