apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  namespace: playground
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: guestbook-ui
  namespace: playground
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`guestbook.k8s.io`)
      services:
        - name: guestbook-ui
          port: 80
