apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: playground
spec:
  project: playground
  source:
    repoURL: 'https://github.com/SIMULATAN/k8s-ops'
    path: playground/guestbook
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: playground
