image:
  tag: 2.6.5

global:
  ldapDomain: simulatan.me
  existingSecret: ldap-admin-passwords

replicaCount: 2

persistence:
  enabled: true
  size: 2Gi

phpldapadmin:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: default-redirect-to-https@kubernetescrd,auth-forwardauth-authelia@kubernetescrd
    hosts:
      - phpldapadmin.simulatan.me

ltb-passwd:
  enabled: false
