apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-black-onion-com
  namespace: blackonion
spec:
  secretName: ssl-black-onion-com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod-http
  dnsNames:
    - "black-onion.com"
    - "www.black-onion.com"
