apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SIMULATAN/k8s-ops
    path: forgejo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: forgejo

