adminUsername: admin

gitea:
  additionalConfigFromEnvs:
    - name: FORGEJO__DATABASE__PASSWD
      valueFrom:
        secretKeyRef:
          name: forgejo-postgres-app
          key: password
  admin:
    existingSecret:
    username:
    password:
  config:
    APP_NAME: "SIMULATAN's Git"
    database:
      DB_TYPE: postgres
      HOST: forgejo-postgres-rw
      NAME: forgejo
      USER: forgejo
      SCHEMA: public
      SSL_MODE: require
    openid:
      ENABLE_OPENID_SIGNUP: true
      ENABLE_OPENID_SIGNIN: false
      WHITELISTED_URIS: auth.simulatan.me
    oauth2_client:
      USERNAME: nickname
      UPDATE_AVATAR: true
    service:
      ALLOW_ONLY_EXTERNAL_REGISTRATION: false
      SHOW_REGISTRATION_BUTTON: false
  oauth:
    - name: Authelia
      iconUrl: https://auth.simulatan.me/favicon.ico
      provider: openidConnect
      autoDiscoverUrl: https://auth.simulatan.me/.well-known/openid-configuration
      scopes: groups email profile
      groupClaimName: groups
      # TODO: replace with `forgejo-admin` once the group is created in LDAP
      adminGroup: forgejo-admin
      existingSecret: forgejo-sso-secret

persistence:
  enabled: true
  claimName: forgejo

redis-cluster:
  cluster:
    nodes: 1
    replicas: 1

postgresql:
  enabled: false
postgresql-ha:
  enabled: false

ingress:
  apiVersion: networking.k8s.io/v1
  enabled: true
  className: traefik
  hosts:
    - host: git.simulatan.me
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - git.simulatan.me
