apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    image:
      repository: traefik
      tag: v2.11.9
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    hostNetwork: true
    #additionalArguments:
      #- "--tracing=true"
