apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    image:
      repository: traefik
      tag: v3.3.4
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    service:
      externalTrafficPolicy: Local
    # additionalArguments:
    #  - "--tracing=true"
