apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud

helmCharts:
- name: nextcloud
  releaseName: nextcloud
  repo: oci://ghcr.io/nextcloud/helm
  version: 7.0.0
  valuesFile: nextcloud.values.yml
  namespace: nextcloud
