apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud

resources:
- ./postgres-cluster.yml

helmCharts:
- name: nextcloud
  releaseName: nextcloud
  repo: oci://ghcr.io/nextcloud/helm
  version: 7.0.0
  valuesFile: nextcloud.values.yml
  namespace: nextcloud
- releaseName: valkey
  name: redis-ha
  repo: https://dandydeveloper.github.io/charts
  version: 4.34.12
  valuesFile: valkey.values.yml
  namespace: nextcloud
