apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud

helmCharts:
- name: nextcloud
  releaseName: nextcloud
  repo: https://nextcloud.github.io/helm/
  version: 6.5.0
  valuesFile: nextcloud.values.yml
  namespace: nextcloud
