global:
  security:
    allowInsecureImages: true # redis was replaced with valkey

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure,web
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-to-https@kubernetescrd
nextcloud:
  host: nc.simulatan.me
  defaultConfigs:
    imaginary.config.php: true
  configs:
    logging.config.php: |-
      <?php
      $CONFIG = array (
        'log_type' => 'file',
        'logfile' => 'nextcloud.log',
        'loglevel' => 2,
        'debug' => false,
        'logdateformat' => 'F d, Y H:i:s'
        );
    proxy.config.php: |-
      <?php
      $CONFIG = array (
        'trusted_proxies' => array(
          0 => '127.0.0.1',
          1 => '10.0.0.0/8',
        ),
        'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
        'overwriteprotocol' => 'https'
      );
    previews.config.php: |-
      <?php
      $CONFIG = array (
        'preview_ffmpeg_path' => '/usr/bin/ffmpeg',
        'enabledPreviewProviders' => array (
          'OC\Preview\Imaginary',
          'OC\Preview\ImaginaryPDF',
          'OC\Preview\BMP',
          // 'OC\Preview\GIF',
          'OC\Preview\HEIC',
          // 'OC\Preview\JPEG',
          'OC\Preview\Krita',
          'OC\Preview\MarkDown',
          'OC\Preview\Movie',
          'OC\Preview\MP3',
          'OC\Preview\OpenDocument',
          // 'OC\Preview\PNG',
          'OC\Preview\SVG',
          'OC\Preview\TXT',
          'OC\Preview\XBitmap',
        ),
      );
  phpConfigs:
    zz-memory_limit.ini: |-
      memory_limit=1024M
    zz-apc.ini: |-
      apc.shm_size=128M
    opcache.conf: |
      php_admin_value[memory_limit] = -1
      php_admin_value[opcache.jit_buffer_size] = 8M
      php_admin_value[opcache.interned_strings_buffer] = 64
      php_admin_value[opcache.memory_consumption] = 512
      php_admin_value[opcache.max_accelerated_files] = 30000
      php_admin_value[opcache.revalidate_freq] = 60
  extraEnv:
    - name: OVERWRITECLIURL
      value: https://nc.simulatan.me
  existingSecret:
    enabled: true
    secretName: nextcloud-secret
    usernameKey: USER
    passwordKey: PASSWORD
cronjob:
  enabled: true
persistence:
  enabled: true
  existingClaim: nextcloud
  # second pvc for the data folder in nextcloud
  nextcloudData:
    enabled: true
    size: 20Gi
    existingClaim: nextcloud-data
internalDatabase:
  enabled: false
externalDatabase:
  enabled: true
  type: postgresql
  existingSecret:
    enabled: true
    secretName: nextcloud-postgres
    usernameKey: USER_NAME
    passwordKey: USER_PW
postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        existingSecret: nextcloud-postgres
        secretKeys:
          adminPasswordKey: ADMIN_PW
          userPasswordKey: USER_PW
  primary:
    persistence:
      enabled: true
      existingClaim: nextcloud-postgresql-data
    resources:
      requests:
        cpu: 300m
        memory: 512Mi
        ephemeral-storage: 100Mi
      limits:
        cpu: 500m
        memory: 1.5Gi
        ephemeral-storage: 1Gi
nodeSelector:
  kubernetes.io/hostname: sim-microserv-debian
redis:
  enabled: true
  image:
    repository: bitnami/valkey
    # make sure to update with https://github.com/bitnami/charts/tree/main/bitnami/redis
    tag: 8.0.2-debian-12
  architecture: standalone
  master:
    nodeSelector:
      kubernetes.io/hostname: sim-microserv-debian
  auth:
    enabled: true
    existingSecret: redis
    existingSecretPasswordKey: REDIS_PASSWORD
imaginary:
  enabled: true
lifecycle:
  postStartCommand: ["/bin/bash", "-c", "apt-get update -y && apt-get install ffmpeg -y && apt-get clean autoclean && rm -rf /var/lib/{apt,dpkg}"]
