ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure,web
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-to-https@kubernetescrd
nextcloud:
  host: nc.simulatan.me
  configs:
    proxy.config.php: |-
      <?php
      $CONFIG = array (
        'trusted_proxies' => array(
          0 => '127.0.0.1',
          1 => '10.0.0.0/8',
        ),
        'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
        'overwriteprotocol' => 'https'
      );
  phpConfigs:
    zz-memory_limit.init: |-
      memory_limit=1024M
  existingSecret:
    enabled: true
    secretName: nextcloud-secret
    usernameKey: USER
    passwordKey: PASSWORD
cronjob:
  enabled: true
persistence:
  enabled: true
  existingClaim: nextcloud
  # second pvc for the data folder in nextcloud
  nextcloudData:
    enabled: true
    size: 20Gi
    existingClaim: nextcloud-data
internalDatabase:
  enabled: false
externalDatabase:
  enabled: true
  type: postgresql
  existingSecret:
    enabled: true
    secretName: nextcloud-postgres
    usernameKey: USER_NAME
    passwordKey: USER_PW
postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        existingSecret: nextcloud-postgres
        secretKeys:
          adminPasswordKey: ADMIN_PW
          userPasswordKey: USER_PW
  primary:
    persistence:
      enabled: true
      existingClaim: nextcloud-postgresql-data
nodeSelector:
  kubernetes.io/hostname: sim-microserv-debian
redis:
  enabled: true
  image:
    repository: bitnami/valkey
    # make sure to update with https://github.com/bitnami/charts/tree/main/bitnami/redis
    tag: 7.2.5-debian-12-r9
  architecture: standalone
  master:
    nodeSelector:
      kubernetes.io/hostname: sim-microserv-debian
  auth:
    enabled: true
    existingSecret: redis
    existingSecretPasswordKey: REDIS_PASSWORD
