apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  project: default
  sources:
    - chart: nextcloud
      repoURL: https://nextcloud.github.io/helm/
      targetRevision: 4.6.7
      helm:
        valueFiles:
          - $k8s-ops/nextcloud/nextcloud.values.yml
    - repoURL: https://github.com/SIMULATAN/k8s-ops
      targetRevision: HEAD
      ref: k8s-ops
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nextcloud
