apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SIMULATAN/k8s-ops
    path: nextcloud
  destination:
    name: in-cluster
    namespace: nextcloud
