apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis
  namespace: nextcloud
spec:
  encryptedData:
    REDIS_PASSWORD: AgA8lBazFS9YxgdtXNu6KhBTfiUJx/4h4DVUB897hlH/Os1WgMBujc2e8eYNMHCbMk2GrUZjm02zhyj7JZ8OMyQW36hqQ1lm/UJq0REIrU43IH31F7UKVz6T9ykquh+Q7vhb6lh3LaoNmLr9lWVJrqX7EEzDYF8gOyQfAsngS7zhtr9EYIg1nvdJ32amvvcmo5axhs86REuP9zzlcFZj0gzz0U1s/nnu/L79TUyx5ArZLNQApAtdRHaxiSUyauPvJgSA14bEup0wLZmEuK5q3KggD01N7VfNWiBPfbEkPTHkZZGm3cxlgu8wZSRl98z5bbA2J3iS2Php3tndvCBzrl3jPQYgzViY8SelE0GuOXXnvMjrLcA9AQ94UtK8en5eBKB+TUz+l6D3xvvTMHjCt3yOWFg7DdzCjDk+N0DuDSOQMJR6DXznlFvM8vQgfwZi+j0h51J/C8xkiNYxV/ufoHRtNn8FcDnxUB6biUt5dH1dzstOTUEf5CRr1uzlTKczQbMRW3fWTdQGJ2UleNaX+FSmOA24h9WhpXBGgypTviGSxtmXSs/AFqsEZMkYsdiClqdii6+fKU92rRUPCvZ1Xe6IYiiGbnZRK3CnLW4CWMqo5ULdBisPzBPBk4mI2pbGTyYrlu3iE/knDmSDuQ1HqazjcHEGeQrBCyGNy6auL+qcTCGCqxKaeJIR4QHkwBWVwtEickYBD01eSv2KKfIAudyjtv55bc0i50869CEw2T9iikiAr2Q5svEoIL/NZjbIPzHgv/cXv2So/og0xTrYEYwx
  template:
    metadata:
      name: redis
      namespace: nextcloud
