apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SIMULATAN/k8s-ops
    path: sealed-secrets
  destination:
    name: in-cluster
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: cluster-hetzner1
spec:
  project: hetzner1
  source:
    repoURL: https://github.com/SIMULATAN/k8s-ops
    path: sealed-secrets
  destination:
    name: hetzner1
