apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgAjifzX47hgS36XncZ2VPuckbnat436E9F/vbac3qRpAPhfj5mT7Bl94VO5zrdxV4I2ZRwpGIVC7+QKWjaszy4ldOfwU/0Fz/uwafUs303ysvTR3LIC8G6PltDoizKkPP2wAKmum9cXasRArrK5Ma+dwvE7D9iLAVtkDo5TOp8AQcN6f/RW+T3tprDupLgq184fWu7ahj5UmhOmY28dotlFI2Jusx60kCRza+eV6dId30fJ1BO+cPIIPWuTXlBTsHe9lmi9MgLdsD1mlz08Tb7oU9VgT6VIbeSR2jZUeTzkNCKQ2Bq22tUplndvrFc4VdG4tlHrjkv6fAwR4rTTDK4lZghPm2S80E5t79Z8GeuWwTQNk4XEig3qS/tz2551g5P/uDWZMTbWlow4BazqxJaxFrKUjW8FG4SDqeG3UYoT33BtBTDK8HT16U4eAGXpqODQfJOtQ4h0IuaXzm4xTc1DyTgn8LMbbHBMcW/VWlLldxnqAw6sOJ2vjsssxB/SPuxmouNhUBPxzfTMCY3K0JMb1EZCTycl/JERjTrfRPVUpBcFztjEnTHf2nVEPWxelo2I7rJYWMe+lKub00rXP8kmh/RPCd1DY5A3jXToPwK5TVzu5PfqlbkPs5SpQhvuYKPIPrOlROPIf16EUSPc36dxIQHdowaU85E0MQ+FQx2yaoSN+FPGaI5ehh+vRSg5mEkly5VS65D+B5IsxbEXwq882iA/kLY5chw1iksEsELHpYlu+FOOG+7d
  template:
    metadata:
      name: cloudflare-token-secret
      namespace: cert-manager
