apiVersion: apps/v1
kind: Deployment
metadata:
  name: mazanoke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mazanoke
  template:
    metadata:
      labels:
        app: mazanoke
    spec:
      containers:
        - image: ghcr.io/civilblur/mazanoke:v1.1.5
          name: mazanoke
          ports:
          - containerPort: 80
