apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vikunja-postgres
spec:
  # TODO: bump to 3
  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:17

  bootstrap:
    initdb:
      database: vikunja
      owner: vikunja

  postgresql:
    pg_hba:
      - local all all trust
      - host all all 127.0.0.1/32 trust
      - host all all ::1/128 trust

  storage:
    size: 1Gi

  monitoring:
    enablePodMonitor: true
