apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 5.5.0
    helm:
      valuesObject:
        redis:
          architecture: replication
        server:
          # external TLS is handled by traefik
          insecure: true
          url: argocd.simulatan.me
          replicaCount: 2
          config:
            kustomize.buildOptions: --enable-helm
          ingress:
            enabled: true
            hostname: argocd.simulatan.me
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: 'true'
          ingressGrpc:
            enabled: true
            hostname: argocd.simulatan.me
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: 'true'
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd

