apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.sync-operation-change.github: ""
spec:
  project: default
  source:
    repoURL: https://github.com/SIMULATAN/k8s-ops
    path: argocd
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd

