alloy:
  stabilityLevel: experimental
  clustering:
    enabled: true

crds:
  create: true

mounts:
  varlog: true

serviceMonitor:
  enabled: true

extraPorts:
  - name: faro
    port: 12347
    targetPort: 12347
    protocol: TCP
    appProtocol: h2c
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
    protocol: TCP

ingress:
  # Faro (Frontend RUM)
  enabled: true
  hosts:
    - faro.monitoring.simulatan.me
