alloy:
  stabilityLevel: experimental
  clustering:
    enabled: true

crds:
  create: true

mounts:
  varlog: true

serviceMonitor:
  enabled: true

extraPorts:
  - name: "faro"
    port: 12347
    targetPort: 12347
    protocol: "TCP"
    appProtocol: "h2c"

ingress:
  # Faro (Frontend RUM)
  enabled: true
  hosts:
    - faro.monitoring.simulatan.me
