apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alloy
spec:
  groups:
  - name: alloy
    rules:
      - alert: GrafanaAlloyServiceDown
        expr: count by (instance) (alloy_build_info) unless count by (instance) (alloy_build_info offset 2m)
        for: 2m
        keep_firing_for: 2m
        labels:
          severity: critical
        annotations:
          summary: Grafana Alloy service down (instance {{ $labels.instance }})
          description: "Alloy on (instance {{ $labels.instance }}) is not responding or has stopped running."

