apiVersion: v1
kind: ConfigMap
metadata:
  name: lldap
data:
  TZ: Europe/Vienna
  GID: "1000"
  UID: "1000"
  LLDAP_VERBOSE: "true"
  LLDAP_LDAP_BASE_DN: "dc=simulatan,dc=me"
  LLDAP_LDAPS_OPTIONS__ENABLED: "true"
  LLDAP_LDAPS_OPTIONS__CERT_FILE: "/secrets/tls.crt"
  LLDAP_LDAPS_OPTIONS__KEY_FILE: "/secrets/tls.key"
