apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lldap
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SIMULATAN/k8s-ops
    path: auth/lldap
  destination:
    name: in-cluster
    namespace: auth

