apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: lldap-postgres
spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:17

  bootstrap:
    initdb:
      database: lldap
      owner: lldap

  postgresql:
    pg_hba:
      - local all all trust
      - host all all 127.0.0.1/32 trust
      - host all all ::1/128 trust

  storage:
    size: 512Mi
