apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnativepg-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SIMULATAN/k8s-ops
    path: cnpg
  destination:
    name: in-cluster
    namespace: cnpg-system
  syncPolicy:
    syncOptions:
      - ServerSideApply=true

