apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnativepg-operator
  namespace: argocd
spec:
  project: default
  sources:
    - chart: cloudnative-pg
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.20.2
      helm:
        valuesObject:
          replicaCount: 2

  destination:
    server: "https://kubernetes.default.svc"
    namespace: cnpg-system

