apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cnpg-system

helmCharts:
- name: cloudnative-pg
  releaseName: cloudnativepg-operator
  repo: https://cloudnative-pg.github.io/charts
  valuesFile: cnpg.values.yml
  version: 0.23.0

