apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cnpg-system

resources:
- https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/refs/tags/v1.26.0/docs/src/samples/monitoring/prometheusrule.yaml
- ./podlogs.yml

helmCharts:
- name: cloudnative-pg
  releaseName: cloudnativepg-operator
  repo: https://cloudnative-pg.github.io/charts
  valuesFile: cnpg.values.yml
  version: 0.23.2

