apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wakapi

resources:
- postgres-cluster.yml
- wakapi-smtp.yml

helmCharts:
- name: wakapi
  releaseName: wakapi
  repo: https://charts.simulatan.me
  valuesFile: wakapi.values.yml
  version: 1.1.1

patches:
  - target:
      version: v1
      kind: ConfigMap
    patch: |-
      - op: add
        path: /data/WAKAPI_PUBLIC_URL
        value: https://wakapi.simulatan.me
