apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wakapi

resources:
- postgres-cluster.yml

helmCharts:
- name: wakapi
  releaseName: wakapi
  repo: https://simulatan.github.io/wakapi-helm-chart/
  valuesFile: wakapi.values.yml
  version: 1.1.0

