apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: wakapi-postgres-cluster
  namespace: wakapi
spec:
  teamId: wakapi
  volume:
    size: 200Mi
  numberOfInstances: 2
  users:
    wakapi:
    - superuser
    - createdb
  databases:
    wakapi: wakapi
  postgresql:
    version: "15"
    parameters:
      listen: "*"
      max_wal_senders: 5
      unix_socket_directories: "/controller/run"
