persistence:
  enabled: false

wakapi_config:
  env: production
  db:
    dialect: postgres
    host: wakapi-postgres-cluster.wakapi.svc.cluster.local
    port: 5432
    name: wakapi
    user: wakapi
    ssl: true
    password_secret:
      enabled: true
      name: wakapi.wakapi-postgres-cluster.credentials.postgresql.acid.zalan.do
  mail:
    enabled: true
    sender: Wakapi <wakapi@smtp.simulatan.me>
    smtp:
      host: live.smtp.mailtrap.io
      port: 587
      # STARTTLS is used instead which requires you to set this to false..
      tls: false
      username: api
      password_secret:
        enabled: true
        name: wakapi-smtp

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: 'true'
  hosts:
    - host: wakapi.simulatan.me
      paths:
        - '/'
