apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wakapi
  namespace: argocd
spec:
  project: default
  source:
    chart: wakapi/wakapi
    repoURL: https://andreymaznyak.github.io/wakapi-helm-chart/
    targetRevision: 1.0.2
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default

