apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wakapi
  namespace: argocd
spec:
  project: default
  source:
    chart: wakapi
    repoURL: https://simulatan.github.io/wakapi-helm-chart/
    targetRevision: 1.0.3
    helm:
      valuesObject:
        image:
          tag: '2.10'
        wakapi_config:
          env: production
        ingress:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: true
          hosts:
            - host: wakapi.k8s.io
              paths: []
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default

