apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wakapi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SIMULATAN/k8s-ops
    path: wakapi
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default

