image:
  repository: ghcr.io/simulatan/wakapi
  tag: '2161c88'

persistence:
  enabled: false

wakapi_config:
  env: production
  db:
    dialect: postgres
    host: wakapi-postgres-cluster.wakapi.svc.cluster.local
    port: 5432
    name: wakapi
    user: wakapi
    ssl: true
    password_secret:
      enabled: true
      name: wakapi.wakapi-postgres-cluster.credentials.postgresql.acid.zalan.do

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: 'true'
  hosts:
    - host: wakapi.simulatan.me
      paths:
        - '/'
