apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wakapi
  namespace: argocd
spec:
  project: default
  source:
    chart: wakapi
    repoURL: https://andreymaznyak.github.io/wakapi-helm-chart/
    targetRevision: 1.0.2
    helm:
      valuesObject:
        image:
          repository: ghcr.io/muety/wakapi
          tag: '2.10'
        wakapi_config:
          env: production
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default

