ingress:
  enabled: true
  hosts:
    - host: wiki.simulatan.me
      paths:
        - path: /
          pathType: ImplementationSpecific

postgresql:
  enabled: false
  # these options would be the preferred way, however,
  # even with tls verification disabled, it still errors...
  # I suppose wikijs handles the two methods differently
  # ---------
  # ssl: true
  # postgresqlHost: wikijs-postgres-cluster
  # postgresqlDatabase: wikijs
  # postgresqlUser: wikijs
  # existingSecret: wikijs.wikijs-postgres-cluster.credentials.postgresql.acid.zalan.do
  # existingSecretKey: password

externalPostgresql:
  # dummy value, will be replaced by a kustomize patch
  databaseURL: DUMMY
  NODE_TLS_REJECT_UNAUTHORIZED: '0'
