apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-arch-scheduler
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-arch-scheduler
    repoURL: https://elementtech.github.io/kube-arch-scheduler/
    targetRevision: 0.0.8
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default

