apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: spotify-stats-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "8.2.3"
  featureCompatibilityVersion: "8.0"

  security:
    authentication:
      modes: ["SCRAM"]

  users:
    - name: root
      db: admin
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      passwordSecretRef:
        name: mongodb-passwords
        key: root
      scramCredentialsSecretName: root
      connectionStringSecretName: mongodb-root
    - name: spotify-stats
      db: spotify-stats
      passwordSecretRef:
        name: mongodb-passwords
        key: your-spotify
      roles:
        - name: readWrite
          db: spotify-stats
      scramCredentialsSecretName: spotify-stats
      connectionStringSecretName: mongodb-spotify-stats

  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

  statefulSet:
    spec:
      template:
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: spotify-stats-mongodb-svc
                  topologyKey: kubernetes.io/hostname
                  weight: 100
          containers:
            - name: mongod
              resources:
                requests:
                  cpu: 300m
                  memory: 500Mi
                limits:
                  cpu: 1
                  memory: 768Mi
            - name: mongodb-agent
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
                limits:
                  cpu: 500m
                  memory: 250Mi
