architecture: replicaset
replicaCount: 3
backup:
  enabled: true
  cronjob:
    storage:
      storageClass: storage-pool-big
arbiter:
  enabled: false
auth:
  enabled: false
metrics:
  enabled: false
resources:
  requests:
    cpu: 200m
    ephemeral-storage: 50Mi
    memory: 1Gi
  limits:
    cpu: 750m
    ephemeral-storage: 2Gi
    memory: 1536Mi
