apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-kubernetes-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mongodb-kubernetes-operator
subjects:
  - kind: ServiceAccount
    name: mongodb-kubernetes-operator
    namespace: mongodb-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-kubernetes-appdb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-kubernetes-appdb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mongodb-kubernetes-appdb
subjects:
  - kind: ServiceAccount
    name: mongodb-kubernetes-appdb
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: your-spotify-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "8.0.6"
  featureCompatibilityVersion: "8.0"

  security:
    authentication:
      modes: ["SCRAM"]

  users:
    - name: root
      db: admin
      passwordSecretRef:
        name: mongodb-passwords
        key: root
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: root
    - name: your-spotify
      db: your-spotify
      passwordSecretRef:
        name: mongodb-passwords
        key: your-spotify
      roles:
        - name: readWrite
          db: your-spotify
      scramCredentialsSecretName: your-spotify

  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

  statefulSet:
    spec:
      template:
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: your-spotify-mongodb-svc
                  topologyKey: kubernetes.io/hostname
                  weight: 100
          containers:
            - name: mongod
              resources:
                requests:
                  cpu: 300m
                  memory: 500Mi
                limits:
                  cpu: 1
                  memory: 768Mi
            - name: mongodb-agent
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
                limits:
                  cpu: 500m
                  memory: 250Mi
