apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-simulatan-me
  namespace: kube-system
spec:
  secretName: ssl-simulatan-me
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  commonName: "*.simulatan.me"
  dnsNames:
    - "simulatan.me"
    - "*.simulatan.me"
