apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd # TODO: set to `shared` or something
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: hetzner1
        name: hetzner1
        namespace: cluster-hetzner1
      - cluster: in-cluster
        name: main
        namespace: argocd
  template:
    metadata:
      name: '{{.name}}-cert-manager' # TODO: remove prefix once namespace feature is implemented
      namespace: '{{.namespace}}' # TODO: PR feature (configuration is noop rn)
    spec:
      project: default
      sources:
        - repoURL: https://github.com/SIMULATAN/k8s-ops
          path: cert-manager
        - repoURL: https://github.com/SIMULATAN/k8s-ops
          path: cert-manager/{{.cluster}}
          directory:
      destination:
        name: '{{.cluster}}'
        namespace: cert-manager
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
