apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/SIMULATAN/k8s-ops
      path: cert-manager
    - repoURL: https://github.com/SIMULATAN/k8s-ops
      path: cert-manager/main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: cert-manager
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: cluster-hetzner1
spec:
  project: hetzner1
  sources:
    - repoURL: https://github.com/SIMULATAN/k8s-ops
      path: cert-manager
    - repoURL: https://github.com/SIMULATAN/k8s-ops
      path: cert-manager/hetzner1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    name: hetzner1
    namespace: cert-manager

