apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./provider-letsencrypt-staging.yml
  - ./provider-letsencrypt-prod.yml
  - ./tls-store.yml

helmCharts:
  - name: cert-manager
    releaseName: cert-manager
    namespace: cert-manager
    repo: oci://quay.io/jetstack/charts
    version: v1.18.2
    valuesFile: cert-manager.values.yml
