apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/cert-manager/cert-manager/releases/download/v1.17.1/cert-manager.yaml
- provider-letsencrypt-staging.yml
- provider-letsencrypt-prod.yml
- cert-simulatan-me.yml
- tls-store.yml
