apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: default
spec:
  certificates:
    - secretName: ssl-simulatan-me
  defaultCertificate:
    secretName: ssl-simulatan-me
