apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vencloud

resources:
  - ./configmap.yml
  - ./secret.yml
  - ./valkey.secret.yml
  - ./deployment.yml
  - ./service.yml
  - ./ingress.yml

helmCharts:
- releaseName: valkey
  name: redis-ha
  repo: https://dandydeveloper.github.io/charts
  version: 4.34.12
  valuesFile: valkey.values.yml
  namespace: vencloud
  skipTests: true
