apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vencloud

resources:
  - ./configmap.yml
  - ./secret.yml
  - ./valkey-secret.yml
  - ./deployment.yml
  - ./service.yml
  - ./ingress.yml

helmCharts:
- name: valkey
  repo: oci://registry-1.docker.io/bitnamicharts/
  version: 3.0.15
  valuesFile: valkey.values.yml
  releaseName: vencloud-valkey
  namespace: vencloud
