apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vencloud
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SIMULATAN/k8s-ops
    path: vencloud
  destination:
    name: in-cluster
    namespace: vencloud

